# Numpy 101

Bu challenge’ın amacı Numpy kütüphanesine alışmak, multidimensional array’leri manipüle etmek ve `for` loops kullanmadan bazı linear algebra işlemlerini uygulamaktır. 

💡 Bu challenge boyunca  [Numpy Cheat Sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf) dosyasını kapalı tutmayı unutma.

In [1]:
import numpy as np # Run this cell!

---

**Q1** - Boyutu 10 olan ve yalnızca sıfırlardan (`0`) oluşan bir null vector oluştur ve `ten_zeros` adlı bir değişkene ata.

Şu şekilde görünmelidir:

```
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
```

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.zeros.html"><code>numpy.zeros</code></a></p>
</details>

In [9]:
ten_zeros= np.zeros(10)
ten_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

---

**Q2** - 5’ten 10’a kadar olan değerleri içeren bir vector oluştur ve `five_to_ten` adlı bir değişkene ata.

Şu şekilde görünmelidir:

```
array([ 5,  6,  7,  8,  9, 10])
```

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.arange.html"><code>numpy.arange</code></a></p>
</details>

In [14]:
five_to_ten= np.arange(5,11)
five_to_ten

array([ 5,  6,  7,  8,  9, 10])

---

**Q3** - Aşağıdaki matrisi bir NumPy `ndarray` olarak oluştur ve `A` adlı bir değişkene ata:
$
A = 
\begin{pmatrix}
5 & 9 & 7\\
1 & 0 & 3
\end{pmatrix}
$

<br>
<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.array.html"><code>numpy.array</code></a></p>
    <p>Checkout more about the relationship between<a href="https://stackoverflow.com/questions/15879315/what-is-the-difference-between-ndarray-and-array-in-numpy"><code>numpy.array and numpy.ndarray</code></a></p>
</details>

In [16]:
A= np.array([[5,9,7],[1,0,3]])
A

array([[5, 9, 7],
       [1, 0, 3]])

---
**Q4** - Aşağıdaki matrisi `np.array()`  constructor’ını kullanmadan oluştur ve `B` adlı bir değişkene ata:
$
B = 
\begin{pmatrix}
1 & 1\\
1 & 1
\end{pmatrix}
$

In [17]:
B= np.ones([2,2])
B

array([[1., 1.],
       [1., 1.]])

---

**Q5** - `-1` ile `1` arasında eşit aralıklarla bölünmüş 20 elemanlı bir vector oluştur ve `lin_twenty` adlı bir değişkene ata.

Şu şekilde görünmelidir:

```
array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])
```

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.linspace.html"><code>numpy.linspace</code></a></p>
</details>

In [18]:
lin_twenty= np.linspace(-1, 1, num=20)
lin_twenty

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

---

**Q6** - 3x3 boyutunda bir identity matrix oluştur ve `C` adlı bir değişkene ata:

$
C = 
\begin{pmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{pmatrix}
$

<br>

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.eye.html"><code>numpy.eye</code></a></p>
</details>

In [20]:
C= np.eye(3)
C

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

---

**Q7** - Aşağıdaki `ndarray` ’i oluştur ve `D` adlı bir değişkene ata:  


$
D = 
\begin{pmatrix}
2 & 9 & 7 & 3 & 1 & 5
\end{pmatrix}
$

-`D` değişkenini 2x3’lük bir matrise reshape et ve `E` adlı bir değişkene ata:

$
E = 
\begin{pmatrix}
2 & 9 & 7\\
3 & 1 & 5
\end{pmatrix}
$

<br>

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.reshape.html"><code>numpy.reshape</code></a></p>
</details>

In [21]:
D= np.array([2,9,7,3,1,5])
E= np.reshape(D, (2,3))
E

array([[2, 9, 7],
       [3, 1, 5]])

---

**Q8**: Bu `ndarray` olan `F` ’in ikinci sütununu seç, 4 satır ve 1 sütundan oluşan bir `ndarray` olacak şekilde reshape et ve `reshaped_F` adlı bir değişkene ata:

$
reshaped\_F = 
\begin{pmatrix}
0.?\\
0.?\\
0.?\\
0.?\\
\end{pmatrix}
$

In [22]:
F = np.random.random((4, 5))
print(F)

[[0.55052595 0.91543999 0.73618748 0.36631229 0.5988154 ]
 [0.55069785 0.15757725 0.53380922 0.47064252 0.68586793]
 [0.32593027 0.62462412 0.63499827 0.04210263 0.95430629]
 [0.59192042 0.55821372 0.91243236 0.30327187 0.10229619]]


In [24]:
reshaped_F = F[:, 1].reshape(4, 1)
reshaped_F

array([[0.91543999],
       [0.15757725],
       [0.62462412],
       [0.55821372]])

---

**Q9** - Matrisler`G` ve `H` ’nin toplamını hesapla ve sonucu `gh_sum` adlı bir değişkende sakla:
$
G = 
\begin{pmatrix}
0 & 4\\
-4 & -3\\
1 & 1
\end{pmatrix}
$

$
H =
\begin{pmatrix}
0 & 1\\
1 & -1\\
2 & 3
\end{pmatrix}
$

$
G + H = ?
$


In [25]:
# Here we demonstrate two different approaches to creating a (3,2) Matrix
G = np.array([0, 4, -4, -3, 1, 1]).reshape(3, 2)
print('G: \n', G)
H = np.array([[0, 1], [1, -1], [2, 3]])
print('H: \n', H)

G: 
 [[ 0  4]
 [-4 -3]
 [ 1  1]]
H: 
 [[ 0  1]
 [ 1 -1]
 [ 2  3]]


In [26]:
gh_sum= np.add(G,H)
gh_sum

array([[ 0,  5],
       [-3, -4],
       [ 3,  4]])

## Kodunu Kontrol Et!

Kodunu kontrol etmek için aşağıdaki cell’i çalıştır:

In [27]:
from nbresult import ChallengeResult

result = ChallengeResult('numpy',
    ten=ten_zeros,
    from_five=five_to_ten,
    A=A,
    B=B,
    lin_twenty=lin_twenty,
    C=C,
    E=E,
    F=F,
    reshaped_F=reshaped_F,
    gh_sum=gh_sum
)
result.write()
print(result.check())


============================= test session starts ==============================
platform linux -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /home/gunay/.pyenv/versions/3.12.9/envs/workintech/bin/python
cachedir: .pytest_cache
rootdir: /home/gunay/code/01-Python/01-Programming-Basics/data-numpy/tests
plugins: anyio-4.8.0, typeguard-4.4.2
collecting ... collected 5 items

test_numpy.py::TestNumpy::test_advanced_matrixes_manipulation PASSED     [ 20%]
test_numpy.py::TestNumpy::test_linear_twenty_vector_creation PASSED      [ 40%]
test_numpy.py::TestNumpy::test_matrixes_creation_and_reshaping PASSED    [ 60%]
test_numpy.py::TestNumpy::test_ndarrays_creation PASSED                  [ 80%]
test_numpy.py::TestNumpy::test_vectors_creation PASSED                   [100%]

============================== 5 passed in 0.19s ===============================


💯 You can commit your code:

git add tests/numpy.pickle

git commit -m 'Completed numpy step'

git push origin master

